### ISSUE TITLE
GDAS grib2 files don't have 125, 175, 225, 775, 825, 875 pressure levels which are needed for the current graphcast model

### ISSUE THREAD

**Issue by SadeghTabas-NOAA** [NOAA-EMC/graphcast#21]
The GDAS grib2 data does not account for a few levels (e.g., 125, 175, 225, 775, 825, 875) that are needed for the current graphcast pre-trained model. As we have these levels in the master file from post processing in Gaussian grid, the `gdas_utility.py` for 37 PL, needs to be updated in a way that, it gets the data for those levels in the Gaussian grid and interpolates them to latlon grid to be used for graphcast 37 PL inputs (`wgrib2` is a potential tool for this task).

**Comment by LinlinCui-NOAA** [comment]
@SadeghTabas-NOAA Does vertical interpolation work for this purpose?

**Comment by SadeghTabas-NOAA** [comment]
> @SadeghTabas-NOAA Does vertical interpolation work for this purpose?

we have these pressure levels in the master file, we just did not export them to the grib2 files, we will talk about this on Monday.

**Comment by junwang-noaa** [comment]
@SadeghTabas-NOAA @LinlinCui-NOAA There are two gdas grib files:

gdas.t00z.pgrb2.0p25.f000
gdas.t00z.**pgrb2b**.0p25.f000

The model fields on those pressure levels listed in the issue are in gdas.t00z.pgrb2b.0p25.f000. Please let me know if there is any missing field. Thanks

**Comment by SadeghTabas-NOAA** [comment]
> @SadeghTabas-NOAA @LinlinCui-NOAA There are two gdas grib files:
> 
> gdas.t00z.pgrb2.0p25.f000 gdas.t00z.**pgrb2b**.0p25.f000
> 
> The model fields on those pressure levels listed in the issue are in gdas.t00z.pgrb2b.0p25.f000. Please let me know if there is any missing field. Thanks

Thank you so much @junwang-noaa for this. we will work on it.

**Comment by SadeghTabas-NOAA** [comment]
@junwang-noaa I dont see `gdas.t00z.pgrb2b.0p25.f000` on s3 or NOMADS. Could you please double check? Thanks
