### ISSUE TITLE
Generate grib2 index files for GraphCastGFS forecasts in S3 bucket

### ISSUE THREAD

**Issue by tokiyui** [NOAA-EMC/graphcast#36]
I would like to download NOAA GraphCast Global Forecast System (GFS) data from AWS (e.g. https://noaa-nws-graphcastgfs-pds.s3.amazonaws.com/index.html#graphcastgfs.20240303/00/ forecasts_13_levels/), are there any plans to provide a grib index file?
Please let me know if I'm asking the wrong place.

**Comment by SadeghTabas-NOAA** [comment]
@tokiyui Thanks for your suggestion, we will update you soon. Also, wanted to let you know that we will soon shift to GraphCastGFS V2 which has a better accuracy.

**Comment by tokiyui** [comment]
Thank you for your response regarding the addition of the index file.
