### ISSUE TITLE
grib2 forecasts metadata issue

### ISSUE THREAD

**Issue by SadeghTabas-NOAA** [NOAA-EMC/graphcast#37]
The nc2grib2 script needs to be updated to resolve the issue with grib2 files metadata.

**Comment by LinlinCui-NOAA** [comment]
@SadeghTabas-NOAA Do you know what is the issue with metadata?

**Comment by SadeghTabas-NOAA** [comment]
@LinlinCui-NOAA Please discuss this with @JunDu-NOAA and @junwang-noaa; I remember there were some issues with grib2 metadata, and I also get a warning when I want to open a grib2 file. Thanks

**Comment by junwang-noaa** [comment]
This is related to wgrib2 lib. The issue is closed.
