### ISSUE TITLE
Update module setup for gc_runfcst_hera.sh due to hera upgrade to Rocky8

### ISSUE THREAD

**Issue by TingLei-NOAA** [NOAA-EMC/graphcast#41]
Dear GFS GraphCast experts
It seems the module setup in gc_runfcst_hera.sh doesn't work after the recent Rocky 8 upgrade on hera.
The below dir doesn't exist now:
```
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env/install/modulefiles/Core

````
What new modules should be used now?
Thanks!

**Comment by SadeghTabas-NOAA** [comment]
@TingLei-NOAA Thanks for letting us know, we will resolve this soon.
